export const BECOMING_RICH = [
  [
    'Investment Education',
    'Networking',
    'Budget Planning',
    'Health Management',
    'Real Estate Investment',
    'Time Management',
    'Career Advancement',
    'Social Skills',
    'Financial Literacy',
  ],
  [
    'Market Research',
    'Building Connections',
    'Expense Tracking',
    'Exercise Routine',
    'Social Skills',
    'Setting Deadlines',
    'Professional Training',
    'Learning New Technologies',
    'Saving Strategies',
  ],
  [
    'Risk Assessment',
    'Community Involvement',
    'Financial Goals',
    'Diet Improvement',
    'Sustainable Spending',
    'Work-Life Balance',
    'Seeking Promotions',
    'Creative Thinking',
    'Investment Planning',
  ],
  [
    'Asset Diversification',
    'Mentorship',
    'Debt Management',
    'Stress Management',
    'Physical Fitness',
    'Efficiency Improvement',
    'Leadership Skills',
    'Adaptability',
    'Emergency Fund Building',
  ],
  [
    'Real Estate Investment',
    'Social Skills',
    'Sustainable Spending',
    'Physical Fitness',
    'Becoming Rich',
    'Effective Communication',
    'Career Growth',
    'Technical Skills',
    'Saving for Retirement',
  ],
  [
    'Portfolio Management',
    'Building Reputation',
    'Credit Score Improvement',
    'Mental Wellbeing',
    'Effective Communication',
    'Task Prioritization',
    'Networking in Industry',
    'Problem Solving',
    'Wealth Management',
  ],
  [
    'Financial Advising',
    'Public Speaking',
    'Creating Budgets',
    'Regular Check-ups',
    'Career Growth',
    'Time Allocation',
    'Personal Branding',
    'Continuous Learning',
    'Estate Planning',
  ],
  [
    'Business Acumen',
    'Collaboration',
    'Cost Cutting',
    'Fitness Goals',
    'Technical Skills',
    'Goal Setting',
    'Professional Networking',
    'Innovation',
    'Tax Optimization',
  ],
  [
    'Start-up Investments',
    'Building Trust',
    'Spending Analysis',
    'Healthy Lifestyle',
    'Saving for Retirement',
    'Prioritizing Tasks',
    'Building Expertise',
    'Advanced Training',
    'Financial Independence',
  ],
]
